-
  name: upload the config file
  tags:
    - haproxy-install
    - haproxy-config
  template: src={{ _haproxy_config_template }}
      dest={{ _haproxy_config_file }} owner=root group=root

-
  name: check the config file
  tags:
    - haproxy-install
    - haproxy-config
  command: service {{ _haproxy_name }} check
  notify:
    - reload haproxy
